# fly.toml app configuration file generated for adelfi on 2023-10-10T17:40:15-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "adelfi"
primary_region = "iad"

[experimental]
  enable_consul = true

[build]

[env]
  DATABASE_URL = "file:app/prisma/litefs/sqlite.db"
  INITIAL_DEPLOYMENT = "false"
  PORT = "8081"
  SCOPES = "write_discounts, read_orders"
  SHOPIFY_API_KEY = "5e08fea9e792973c455f4c456965173a"
  SHOPIFY_APP_URL = "https://adelfi.fly.dev"
  DEFER_TOKEN = "BNKwjF5EP5MeP_ZZU-TjjnSt3QA8d9Pwkoc9--5gEdHD2RiG6saOrp45X1zATOKv"

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[[services]]
  internal_port = 8080
  processess = ["app"]
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
