# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "adelfi-app"
client_id = "9afd9906804ced23e50ebec3c7c4e5e0"
application_url = "https://ns-reduced-excess-nickel.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts"

[auth]
redirect_urls = [
  "https://ns-reduced-excess-nickel.trycloudflare.com/auth/callback",
  "https://ns-reduced-excess-nickel.trycloudflare.com/auth/shopify/callback",
  "https://ns-reduced-excess-nickel.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9f306b3f.myshopify.com"
